package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Computer generated by hbm2java
 */
@Entity
@Table(name = "computer", schema = "public")
public class Computer implements java.io.Serializable,IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String cpu;
	private String ram;

	
	//private List<Device> devices = null;

	public Computer() {
	}

	public Computer(int id) {
		this.id = id;
	}

	public Computer(int id, String cpu, String ram/*, List<Device> devices*/) {
		this.id = id;
		this.cpu = cpu;
		this.ram = ram;
		//this.devices = devices;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cpu")
	public String getCpu() {
		return this.cpu;
	}

	public void setCpu(String cpu) {
		this.cpu = cpu;
	}

	@Column(name = "ram")
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "computer")
	public List<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(List<Device> devices) {
		this.devices = devices;
	}*/

}
