package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", schema = "public")
public class Department implements java.io.Serializable,IEntity  {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private List<User> users = null;
	
	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, List<User> users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


/*	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}
*/
}
