package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", schema = "public")
public class Invoice implements java.io.Serializable,IEntity  {

	private int id;
	private String referenceFile;

	public Invoice() {
	}

	public Invoice(int id) {
		this.id = id;
	}

	public Invoice(int id, String referenceFile) {
		this.id = id;
		this.referenceFile = referenceFile;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "reference_file")
	public String getReferenceFile() {
		return this.referenceFile;
	}

	public void setReferenceFile(String referenceFile) {
		this.referenceFile = referenceFile;
	}

}
