package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Printer generated by hbm2java
 */
@Entity
@Table(name = "printer", schema = "public")
public class Printer implements java.io.Serializable,IEntity  {

	private int id;
	private Boolean wifi;
	private Long faxNumber;
	private Boolean color;
	private String cartridge;
	private String paperType;
	private Boolean scanner;
	private Boolean fax;
	private Boolean photoCopy;
	private List<Device> devices = null;

	public Printer() {
	}

	public Printer(int id) {
		this.id = id;
	}

	public Printer(int id, Boolean wifi, Long faxNumber, Boolean color, String cartridge, String paperType,
			Boolean scanner, Boolean fax, Boolean photoCopy, List<Device> devices) {
		this.id = id;
		this.wifi = wifi;
		this.faxNumber = faxNumber;
		this.color = color;
		this.cartridge = cartridge;
		this.paperType = paperType;
		this.scanner = scanner;
		this.fax = fax;
		this.photoCopy = photoCopy;
		this.devices = devices;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "wifi")
	public Boolean getWifi() {
		return this.wifi;
	}

	public void setWifi(Boolean wifi) {
		this.wifi = wifi;
	}

	@Column(name = "fax_number")
	public Long getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(Long faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Column(name = "color")
	public Boolean getColor() {
		return this.color;
	}

	public void setColor(Boolean color) {
		this.color = color;
	}

	@Column(name = "cartridge")
	public String getCartridge() {
		return this.cartridge;
	}

	public void setCartridge(String cartridge) {
		this.cartridge = cartridge;
	}

	@Column(name = "paper_type")
	public String getPaperType() {
		return this.paperType;
	}

	public void setPaperType(String paperType) {
		this.paperType = paperType;
	}

	@Column(name = "scanner")
	public Boolean getScanner() {
		return this.scanner;
	}

	public void setScanner(Boolean scanner) {
		this.scanner = scanner;
	}

	@Column(name = "fax")
	public Boolean getFax() {
		return this.fax;
	}

	public void setFax(Boolean fax) {
		this.fax = fax;
	}

	@Column(name = "photo_copy")
	public Boolean getPhotoCopy() {
		return this.photoCopy;
	}

	public void setPhotoCopy(Boolean photoCopy) {
		this.photoCopy = photoCopy;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "printer")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}*/

}
