package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name = "registration", schema = "public")
public class Registration implements java.io.Serializable,IEntity  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Device device;
	private User user;
	private String dateRented;
	private String dateReturn;
	private Boolean latestRegistration;

	public Registration() {
	}

	public Registration(int id) {
		this.id = id;
	}

	public Registration(int id, Device device, User user, String dateRented, String dateReturn,
			Boolean latestRegistration) {
		this.id = id;
		this.device = device;
		this.user = user;
		this.dateRented = dateRented;
		this.dateReturn = dateReturn;
		this.latestRegistration = latestRegistration;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "date_rented", length = 15)
	public String getDateRented() {
		return this.dateRented;
	}

	public void setDateRented(String dateRented) {
		this.dateRented = dateRented;
	}

	@Column(name = "date_return", length = 15)
	public String getDateReturn() {
		return this.dateReturn;
	}

	public void setDateReturn(String dateReturn) {
		this.dateReturn = dateReturn;
	}

	@Column(name = "latest_registration")
	public Boolean getLatestRegistration() {
		return this.latestRegistration;
	}

	public void setLatestRegistration(Boolean latestRegistration) {
		this.latestRegistration = latestRegistration;
	}

}
