package entities.impl;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import dao.interf.IEntity;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", schema = "public")
public class Stock implements java.io.Serializable,IEntity  {

	private int id;
	private Product product;
	private Integer quantity;
	private Integer maxQuantity;
	private Integer minQuantity;

	public Stock() {
	}

	public Stock(int id) {
		this.id = id;
	}

	public Stock(int id, Product product, Integer quantity, Integer maxQuantity, Integer minQuantity) {
		this.id = id;
		this.product = product;
		this.quantity = quantity;
		this.maxQuantity = maxQuantity;
		this.minQuantity = minQuantity;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Override
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	@Override
	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "max_quantity")
	public Integer getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(Integer maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

	@Column(name = "min_quantity")
	public Integer getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(Integer minQuantity) {
		this.minQuantity = minQuantity;
	}

}
