package entities;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * Device generated by hbm2java
 */
@Entity
@JsonRootName("device")
@Table(name = "device", schema = "public")
public class Device implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Computer computer;
	private Location location;
	private Network network;
	private Printer printer;
	private Product product;
	private String condition;
	private String serialNumber;
	private String description;
	
	private List<Registration> registrationList = null;

	public Device() {
	}

	public Device(int id) {
		this.id = id;
	}

	public Device(int id, Computer computer, Location location, Network network, Printer printer, Product product,
			String condition, String serialNumber, String description, List<Registration> registrationList) {
		this.id = id;
		this.computer = computer;
		this.location = location;
		this.network = network;
		this.printer = printer;
		this.product = product;
		this.condition = condition;
		this.serialNumber = serialNumber;
		this.description = description;
		this.registrationList = registrationList;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "computer_id")
	@JsonManagedReference
	public Computer getComputer() {
		return this.computer;
	}

	public void setComputer(Computer computer) {
		this.computer = computer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id")
	@JsonManagedReference
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JsonManagedReference
	@JoinColumn(name = "network_id")
	public Network getNetwork() {
		return this.network;
	}

	public void setNetwork(Network network) {
		this.network = network;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "printer_id")
	@JsonManagedReference
	public Printer getPrinter() {
		return this.printer;
	}

	public void setPrinter(Printer printer) {
		this.printer = printer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	@JsonManagedReference
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "condition")
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Column(name = "serial_number")
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Transient
	public List<Registration> getRegistrationList() {
		return this.registrationList;
	}

	public void setRegistrationList(List<Registration> registrationList) {
		this.registrationList = registrationList;
	}

}
