package entities;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Network generated by hbm2java
 */
@Entity
@Table(name = "network", schema = "public")
public class Network implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String server;
	private String dns;
	private String ipAddress;
	private List<Device> devices = null;

	public Network() {
	}

	public Network(int id) {
		this.id = id;
	}

	public Network(int id, String server, String dns, String ipAddress, List<Device> devices) {
		this.id = id;
		this.server = server;
		this.dns = dns;
		this.ipAddress = ipAddress;
		this.devices = devices;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "server")
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "dns")
	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

	@Column(name = "ip_address", length = 16)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "network")
	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}*/

}
