package entities;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone", schema = "public")
public class Phone implements java.io.Serializable {

	private int id;
	private String carrier;
	private Integer simCard;
	private Integer imei;
	private Integer phoneNumber;

	public Phone() {
	}

	public Phone(int id) {
		this.id = id;
	}

	public Phone(int id, String carrier, Integer simCard, Integer imei, Integer phoneNumber) {
		this.id = id;
		this.carrier = carrier;
		this.simCard = simCard;
		this.imei = imei;
		this.phoneNumber = phoneNumber;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "carrier")
	public String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	@Column(name = "sim_card")
	public Integer getSimCard() {
		return this.simCard;
	}

	public void setSimCard(Integer simCard) {
		this.simCard = simCard;
	}

	@Column(name = "imei")
	public Integer getImei() {
		return this.imei;
	}

	public void setImei(Integer imei) {
		this.imei = imei;
	}

	@Column(name = "phone_number")
	public Integer getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
