package entities;
// Generated 16-Aug-2017 3:49:11 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", schema = "public")
public class Photo implements java.io.Serializable {

	private int id;
	private String referenceFile;

	public Photo() {
	}

	public Photo(int id) {
		this.id = id;
	}

	public Photo(int id, String referenceFile) {
		this.id = id;
		this.referenceFile = referenceFile;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "reference_file")
	public String getReferenceFile() {
		return this.referenceFile;
	}

	public void setReferenceFile(String referenceFile) {
		this.referenceFile = referenceFile;
	}

}
