package proxies;
// Generated 30-Jun-2017 10:18:43 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "departments", schema = "public")
public class DepartmentsProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@JsonProperty
	private int id;
	@JsonProperty
	private String name;
	//private Set<Users> userses = new HashSet<Users>(0);

	public DepartmentsProxy() {
	}

	public DepartmentsProxy(int id) {
		this.id = id;
	}

	public DepartmentsProxy(int id, String name/*, Set<Users> userses*/) {
		this.id = id;
		this.name = name;
		//this.userses = userses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}*/

}
