package proxies;
// Generated 30-Jun-2017 10:18:43 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Devices generated by hbm2java
 */
@Entity
@Table(name = "devices", schema = "public")
public class DevicesProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@JsonProperty
	private int id;
	//@JsonProperty
	/*private Locations locations;
	@JsonProperty
	private Users users;
	@JsonProperty
	private Network network;*/


	public DevicesProxy() {
	}

	public DevicesProxy(int id/*, Locations locations, Users users*/) {
		this.id = id;

	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"locationId\"")
	@JsonUnwrapped
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"userId\"")
	@JsonUnwrapped
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	

	public Network getNetwork() {
		return this.network;
	}

	public void setNetwork(Network network) {
		this.network = network;
	}*/


	
	

}
