package proxies;
// Generated 30-Jun-2017 10:18:43 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "locations", schema = "public")
public class LocationsProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@JsonProperty
	private int id;
	@JsonProperty
	private String address;
	@JsonProperty
	private String city;
	@JsonProperty
	private String country;
	@JsonProperty
	private String postalCode;
	@JsonProperty
	private String latitude;
	@JsonProperty
	private String longitude;


	public LocationsProxy() {
	}

	public LocationsProxy(int id) {
		this.id = id;
	}

	public LocationsProxy(int id, String address, String city, String country, String postalCode, String latitude,
			String longitude/*, Set<Devices> deviceses*/) {
		this.id = id;
		this.address = address;
		this.city = city;
		this.country = country;
		this.postalCode = postalCode;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "\"postalCode\"")
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "latitude")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<Devices> getDeviceses() {
	
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
	
		this.deviceses = deviceses;
	}*/

}
