package proxies;
// Generated 5-Jul-2017 1:37:25 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Network generated by hbm2java
 */
@Entity
@Table(name = "network", schema = "public")
public class NetworkProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@JsonProperty
	private int id;
	@JsonProperty
	private String server;
	@JsonProperty
	private String dns;
	@JsonProperty
	private String ipAddress;
	//private Set<Devices> deviceses = new HashSet<Devices>(0);

	public NetworkProxy() {
	}

	public NetworkProxy(int id) {
		this.id = id;
	}

	public NetworkProxy(int id, String server, String dns, String ipAddress/*, Set<Devices> deviceses*/) {
		this.id = id;
		this.server = server;
		this.dns = dns;
		this.ipAddress = ipAddress;
		//this.deviceses = deviceses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "server")
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "dns")
	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}

	@Column(name = "\"ipAddress\"", length = 16)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "network")
	public Set<Devices> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
		this.deviceses = deviceses;
	}*/

}
