package proxies;
// Generated 30-Jun-2017 10:18:43 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "public")
public class UsersProxy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@JsonProperty
	private int id;
	@JsonProperty
	private DepartmentsProxy departments;
	@JsonProperty
	private String firstName;
	@JsonProperty
	private String lastName;
	@JsonProperty
	private String companyTitle;
	@JsonProperty
	private String middleName;
	//private Set<Devices> deviceses = new HashSet<Devices>(0);

	public UsersProxy() {
	}

	public UsersProxy(int id) {
		this.id = id;
	}

	public UsersProxy(int id, DepartmentsProxy departments, String firstName, String lastName, String companyTitle/*,
			Set<Devices> deviceses*/) {
		this.id = id;
		this.departments = departments;
		this.firstName = firstName;
		this.lastName = lastName;
		this.companyTitle = companyTitle;
		//this.deviceses = deviceses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"departmentId\"")
	@JsonManagedReference
	public DepartmentsProxy getDepartments() {
		return this.departments;
	}

	public void setDepartments(DepartmentsProxy departments) {
		this.departments = departments;
	}

	@Column(name = "\"firstName\"")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "\"lastName\"")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "\"companyTitle\"")
	public String getCompanyTitle() {
		return this.companyTitle;
	}

	public void setCompanyTitle(String companyTitle) {
		this.companyTitle = companyTitle;
	}
	
	@Column(name = "\"middleName\"")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Devices> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
		this.deviceses = deviceses;
	}*/

}
